### ISSUE TITLE
Remapped keybindings lost when attaching

### ISSUE THREAD

**Issue by ShaitanLyss** [luccahuguet/yazelix#40]
I use gnome terminal and zsh. Yazelix works as intended when creating sessions, but when attaching to them it goes back to default bindings. The weird part is that the ui still shows the new bindings.

**Comment by ShaitanLyss** [comment]
Ressurecting also works weirdly

**Comment by luccahuguet** [comment]
hi there, thank you! 

it seems that the odd behavior comes from the live config reload from zellij's newest version

we'll have to investigate about this..

**Comment by luccahuguet** [comment]
I think this commit will fix this: https://github.com/Tomcat-42/zellij/commit/b099718acbc986a27ac148379a07b979061ba599

for now I don't think there is much to be done

should the weird behavior continue in the future, what I could do is move the keybinding remaps straight to zellijs config, instead of living inside the layout

**Comment by luccahuguet** [comment]
@ShaitanLyss can you try the v5 branch? 

it is working for me now

**Comment by ShaitanLyss** [comment]
Hey, it seems to be working! Thanks

**Comment by luccahuguet** [comment]
amazing!, im closing this now

and I will merge v5 into main when I have time

**Comment by luccahuguet** [comment]
thank for your help
